//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("SesaModel", "InternalMaterialProductMaterial", "Material", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Sesa.Desktop.Models.Material), "ProductMaterialTable", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Sesa.Desktop.Models.InternalProductMaterial))]
[assembly: EdmRelationshipAttribute("SesaModel", "InternalProductProductMaterial", "Product", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Sesa.Desktop.Models.Product), "ProductMaterialTable", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Sesa.Desktop.Models.InternalProductMaterial))]
[assembly: EdmRelationshipAttribute("SesaModel", "UnitMaterial", "Unit", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Sesa.Desktop.Models.Unit), "Material", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Sesa.Desktop.Models.Material))]
[assembly: EdmRelationshipAttribute("SesaModel", "MaterialWarehouseBillDetail", "Material", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Sesa.Desktop.Models.Material), "WarehouseBillDetail", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Sesa.Desktop.Models.WarehouseBillDetail))]
[assembly: EdmRelationshipAttribute("SesaModel", "WarehouseBillWarehouseBillDetail", "WarehouseBill", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Sesa.Desktop.Models.WarehouseBill), "WarehouseBillDetail", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Sesa.Desktop.Models.WarehouseBillDetail))]
[assembly: EdmRelationshipAttribute("SesaModel", "UnitWarehouseBillDetail", "Unit", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Sesa.Desktop.Models.Unit), "WarehouseBillDetail", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Sesa.Desktop.Models.WarehouseBillDetail))]
[assembly: EdmRelationshipAttribute("SesaModel", "ProductProductionTestimony", "Product", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Sesa.Desktop.Models.Product), "ProductionTestimony", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Sesa.Desktop.Models.Testimony))]
[assembly: EdmRelationshipAttribute("SesaModel", "TestimonyTestimonyDetail", "Testimony", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Sesa.Desktop.Models.Testimony), "TestimonyDetail", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Sesa.Desktop.Models.TestimonyDetail))]
[assembly: EdmRelationshipAttribute("SesaModel", "WarehouseBillTestimonyDetail", "WarehouseBill", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Sesa.Desktop.Models.WarehouseBill), "TestimonyDetail", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Sesa.Desktop.Models.TestimonyDetail))]
[assembly: EdmRelationshipAttribute("SesaModel", "MaterialTestimonyDetail", "Material", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Sesa.Desktop.Models.Material), "TestimonyDetail", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Sesa.Desktop.Models.TestimonyDetail))]
[assembly: EdmRelationshipAttribute("SesaModel", "ProductExternalProductMaterial", "Product", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Sesa.Desktop.Models.Product), "ExternalProductMaterial", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Sesa.Desktop.Models.ExternalProductMaterial))]
[assembly: EdmRelationshipAttribute("SesaModel", "MaterialExternalProductMaterial", "Material", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Sesa.Desktop.Models.Material), "ExternalProductMaterial", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Sesa.Desktop.Models.ExternalProductMaterial))]
[assembly: EdmRelationshipAttribute("SesaModel", "FK_BaseUnit_DerivedUnit", "Unit", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Sesa.Desktop.Models.Unit), "Unit1", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Sesa.Desktop.Models.Unit), true)]

#endregion

namespace Sesa.Desktop.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SesaModelContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SesaModelContainer object using the connection string found in the 'SesaModelContainer' section of the application configuration file.
        /// </summary>
        public SesaModelContainer() : base("name=SesaModelContainer", "SesaModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SesaModelContainer object.
        /// </summary>
        public SesaModelContainer(string connectionString) : base(connectionString, "SesaModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SesaModelContainer object.
        /// </summary>
        public SesaModelContainer(EntityConnection connection) : base(connection, "SesaModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Product> Product
        {
            get
            {
                if ((_Product == null))
                {
                    _Product = base.CreateObjectSet<Product>("Product");
                }
                return _Product;
            }
        }
        private ObjectSet<Product> _Product;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Material> Material
        {
            get
            {
                if ((_Material == null))
                {
                    _Material = base.CreateObjectSet<Material>("Material");
                }
                return _Material;
            }
        }
        private ObjectSet<Material> _Material;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<InternalProductMaterial> InternalProductMaterial
        {
            get
            {
                if ((_InternalProductMaterial == null))
                {
                    _InternalProductMaterial = base.CreateObjectSet<InternalProductMaterial>("InternalProductMaterial");
                }
                return _InternalProductMaterial;
            }
        }
        private ObjectSet<InternalProductMaterial> _InternalProductMaterial;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Unit> Unit
        {
            get
            {
                if ((_Unit == null))
                {
                    _Unit = base.CreateObjectSet<Unit>("Unit");
                }
                return _Unit;
            }
        }
        private ObjectSet<Unit> _Unit;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<WarehouseBill> WarehouseBill
        {
            get
            {
                if ((_WarehouseBill == null))
                {
                    _WarehouseBill = base.CreateObjectSet<WarehouseBill>("WarehouseBill");
                }
                return _WarehouseBill;
            }
        }
        private ObjectSet<WarehouseBill> _WarehouseBill;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<WarehouseBillDetail> WarehouseBillDetail
        {
            get
            {
                if ((_WarehouseBillDetail == null))
                {
                    _WarehouseBillDetail = base.CreateObjectSet<WarehouseBillDetail>("WarehouseBillDetail");
                }
                return _WarehouseBillDetail;
            }
        }
        private ObjectSet<WarehouseBillDetail> _WarehouseBillDetail;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Testimony> Testimony
        {
            get
            {
                if ((_Testimony == null))
                {
                    _Testimony = base.CreateObjectSet<Testimony>("Testimony");
                }
                return _Testimony;
            }
        }
        private ObjectSet<Testimony> _Testimony;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TestimonyDetail> TestimonyDetail
        {
            get
            {
                if ((_TestimonyDetail == null))
                {
                    _TestimonyDetail = base.CreateObjectSet<TestimonyDetail>("TestimonyDetail");
                }
                return _TestimonyDetail;
            }
        }
        private ObjectSet<TestimonyDetail> _TestimonyDetail;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ExternalProductMaterial> ExternalProductMaterial
        {
            get
            {
                if ((_ExternalProductMaterial == null))
                {
                    _ExternalProductMaterial = base.CreateObjectSet<ExternalProductMaterial>("ExternalProductMaterial");
                }
                return _ExternalProductMaterial;
            }
        }
        private ObjectSet<ExternalProductMaterial> _ExternalProductMaterial;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Product EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProduct(Product product)
        {
            base.AddObject("Product", product);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Material EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMaterial(Material material)
        {
            base.AddObject("Material", material);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the InternalProductMaterial EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToInternalProductMaterial(InternalProductMaterial internalProductMaterial)
        {
            base.AddObject("InternalProductMaterial", internalProductMaterial);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Unit EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUnit(Unit unit)
        {
            base.AddObject("Unit", unit);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the WarehouseBill EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToWarehouseBill(WarehouseBill warehouseBill)
        {
            base.AddObject("WarehouseBill", warehouseBill);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the WarehouseBillDetail EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToWarehouseBillDetail(WarehouseBillDetail warehouseBillDetail)
        {
            base.AddObject("WarehouseBillDetail", warehouseBillDetail);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Testimony EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTestimony(Testimony testimony)
        {
            base.AddObject("Testimony", testimony);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TestimonyDetail EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTestimonyDetail(TestimonyDetail testimonyDetail)
        {
            base.AddObject("TestimonyDetail", testimonyDetail);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ExternalProductMaterial EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToExternalProductMaterial(ExternalProductMaterial externalProductMaterial)
        {
            base.AddObject("ExternalProductMaterial", externalProductMaterial);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SesaModel", Name="ExternalProductMaterial")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ExternalProductMaterial : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ExternalProductMaterial object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="value">Initial value of the Value property.</param>
        public static ExternalProductMaterial CreateExternalProductMaterial(global::System.Guid id, global::System.Decimal value)
        {
            ExternalProductMaterial externalProductMaterial = new ExternalProductMaterial();
            externalProductMaterial.Id = id;
            externalProductMaterial.Value = value;
            return externalProductMaterial;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Value
        {
            get
            {
                return _Value;
            }
            set
            {
                OnValueChanging(value);
                ReportPropertyChanging("Value");
                _Value = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Value");
                OnValueChanged();
            }
        }
        private global::System.Decimal _Value;
        partial void OnValueChanging(global::System.Decimal value);
        partial void OnValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Pert
        {
            get
            {
                return _Pert;
            }
            set
            {
                OnPertChanging(value);
                ReportPropertyChanging("Pert");
                _Pert = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Pert");
                OnPertChanged();
            }
        }
        private global::System.Decimal _Pert = 0m;
        partial void OnPertChanging(global::System.Decimal value);
        partial void OnPertChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SesaModel", "ProductExternalProductMaterial", "Product")]
        public Product Product
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("SesaModel.ProductExternalProductMaterial", "Product").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("SesaModel.ProductExternalProductMaterial", "Product").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Product> ProductReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("SesaModel.ProductExternalProductMaterial", "Product");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Product>("SesaModel.ProductExternalProductMaterial", "Product", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SesaModel", "MaterialExternalProductMaterial", "Material")]
        public Material Material
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Material>("SesaModel.MaterialExternalProductMaterial", "Material").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Material>("SesaModel.MaterialExternalProductMaterial", "Material").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Material> MaterialReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Material>("SesaModel.MaterialExternalProductMaterial", "Material");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Material>("SesaModel.MaterialExternalProductMaterial", "Material", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SesaModel", Name="InternalProductMaterial")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class InternalProductMaterial : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new InternalProductMaterial object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="value">Initial value of the Value property.</param>
        public static InternalProductMaterial CreateInternalProductMaterial(global::System.Guid id, global::System.Decimal value)
        {
            InternalProductMaterial internalProductMaterial = new InternalProductMaterial();
            internalProductMaterial.Id = id;
            internalProductMaterial.Value = value;
            return internalProductMaterial;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Value
        {
            get
            {
                return _Value;
            }
            set
            {
                OnValueChanging(value);
                ReportPropertyChanging("Value");
                _Value = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Value");
                OnValueChanged();
            }
        }
        private global::System.Decimal _Value;
        partial void OnValueChanging(global::System.Decimal value);
        partial void OnValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Pert
        {
            get
            {
                return _Pert;
            }
            set
            {
                OnPertChanging(value);
                ReportPropertyChanging("Pert");
                _Pert = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Pert");
                OnPertChanged();
            }
        }
        private global::System.Decimal _Pert = 0m;
        partial void OnPertChanging(global::System.Decimal value);
        partial void OnPertChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SesaModel", "InternalMaterialProductMaterial", "Material")]
        public Material Material
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Material>("SesaModel.InternalMaterialProductMaterial", "Material").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Material>("SesaModel.InternalMaterialProductMaterial", "Material").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Material> MaterialReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Material>("SesaModel.InternalMaterialProductMaterial", "Material");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Material>("SesaModel.InternalMaterialProductMaterial", "Material", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SesaModel", "InternalProductProductMaterial", "Product")]
        public Product Product
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("SesaModel.InternalProductProductMaterial", "Product").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("SesaModel.InternalProductProductMaterial", "Product").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Product> ProductReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("SesaModel.InternalProductProductMaterial", "Product");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Product>("SesaModel.InternalProductProductMaterial", "Product", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SesaModel", Name="Material")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Material : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Material object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="caption">Initial value of the Caption property.</param>
        /// <param name="isFloatValue">Initial value of the IsFloatValue property.</param>
        /// <param name="isPackingType">Initial value of the IsPackingType property.</param>
        public static Material CreateMaterial(global::System.Guid id, global::System.String caption, global::System.Boolean isFloatValue, global::System.Boolean isPackingType)
        {
            Material material = new Material();
            material.Id = id;
            material.Caption = caption;
            material.IsFloatValue = isFloatValue;
            material.IsPackingType = isPackingType;
            return material;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Caption
        {
            get
            {
                return _Caption;
            }
            set
            {
                OnCaptionChanging(value);
                ReportPropertyChanging("Caption");
                _Caption = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Caption");
                OnCaptionChanged();
            }
        }
        private global::System.String _Caption;
        partial void OnCaptionChanging(global::System.String value);
        partial void OnCaptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GramFormula
        {
            get
            {
                return _GramFormula;
            }
            set
            {
                OnGramFormulaChanging(value);
                ReportPropertyChanging("GramFormula");
                _GramFormula = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GramFormula");
                OnGramFormulaChanged();
            }
        }
        private global::System.String _GramFormula;
        partial void OnGramFormulaChanging(global::System.String value);
        partial void OnGramFormulaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsFloatValue
        {
            get
            {
                return _IsFloatValue;
            }
            set
            {
                OnIsFloatValueChanging(value);
                ReportPropertyChanging("IsFloatValue");
                _IsFloatValue = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsFloatValue");
                OnIsFloatValueChanged();
            }
        }
        private global::System.Boolean _IsFloatValue;
        partial void OnIsFloatValueChanging(global::System.Boolean value);
        partial void OnIsFloatValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsPackingType
        {
            get
            {
                return _IsPackingType;
            }
            set
            {
                OnIsPackingTypeChanging(value);
                ReportPropertyChanging("IsPackingType");
                _IsPackingType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsPackingType");
                OnIsPackingTypeChanged();
            }
        }
        private global::System.Boolean _IsPackingType;
        partial void OnIsPackingTypeChanging(global::System.Boolean value);
        partial void OnIsPackingTypeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SesaModel", "InternalMaterialProductMaterial", "ProductMaterialTable")]
        public EntityCollection<InternalProductMaterial> InternalProductMaterials
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<InternalProductMaterial>("SesaModel.InternalMaterialProductMaterial", "ProductMaterialTable");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<InternalProductMaterial>("SesaModel.InternalMaterialProductMaterial", "ProductMaterialTable", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SesaModel", "UnitMaterial", "Unit")]
        public Unit Unit
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Unit>("SesaModel.UnitMaterial", "Unit").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Unit>("SesaModel.UnitMaterial", "Unit").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Unit> UnitReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Unit>("SesaModel.UnitMaterial", "Unit");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Unit>("SesaModel.UnitMaterial", "Unit", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SesaModel", "MaterialWarehouseBillDetail", "WarehouseBillDetail")]
        public EntityCollection<WarehouseBillDetail> WarehouseBillDetails
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<WarehouseBillDetail>("SesaModel.MaterialWarehouseBillDetail", "WarehouseBillDetail");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<WarehouseBillDetail>("SesaModel.MaterialWarehouseBillDetail", "WarehouseBillDetail", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SesaModel", "MaterialTestimonyDetail", "TestimonyDetail")]
        public EntityCollection<TestimonyDetail> TestimonyDetails
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TestimonyDetail>("SesaModel.MaterialTestimonyDetail", "TestimonyDetail");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TestimonyDetail>("SesaModel.MaterialTestimonyDetail", "TestimonyDetail", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SesaModel", "MaterialExternalProductMaterial", "ExternalProductMaterial")]
        public EntityCollection<ExternalProductMaterial> ExternalProductMaterial
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ExternalProductMaterial>("SesaModel.MaterialExternalProductMaterial", "ExternalProductMaterial");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ExternalProductMaterial>("SesaModel.MaterialExternalProductMaterial", "ExternalProductMaterial", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SesaModel", Name="Product")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Product : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Product object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="caption">Initial value of the Caption property.</param>
        /// <param name="validInputPercent">Initial value of the ValidInputPercent property.</param>
        /// <param name="addedValuePercent">Initial value of the AddedValuePercent property.</param>
        public static Product CreateProduct(global::System.Guid id, global::System.String caption, global::System.Decimal validInputPercent, global::System.Decimal addedValuePercent)
        {
            Product product = new Product();
            product.Id = id;
            product.Caption = caption;
            product.ValidInputPercent = validInputPercent;
            product.AddedValuePercent = addedValuePercent;
            return product;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Caption
        {
            get
            {
                return _Caption;
            }
            set
            {
                OnCaptionChanging(value);
                ReportPropertyChanging("Caption");
                _Caption = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Caption");
                OnCaptionChanged();
            }
        }
        private global::System.String _Caption;
        partial void OnCaptionChanging(global::System.String value);
        partial void OnCaptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ValidInputPercent
        {
            get
            {
                return _ValidInputPercent;
            }
            set
            {
                OnValidInputPercentChanging(value);
                ReportPropertyChanging("ValidInputPercent");
                _ValidInputPercent = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ValidInputPercent");
                OnValidInputPercentChanged();
            }
        }
        private global::System.Decimal _ValidInputPercent;
        partial void OnValidInputPercentChanging(global::System.Decimal value);
        partial void OnValidInputPercentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal AddedValuePercent
        {
            get
            {
                return _AddedValuePercent;
            }
            set
            {
                OnAddedValuePercentChanging(value);
                ReportPropertyChanging("AddedValuePercent");
                _AddedValuePercent = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AddedValuePercent");
                OnAddedValuePercentChanged();
            }
        }
        private global::System.Decimal _AddedValuePercent;
        partial void OnAddedValuePercentChanging(global::System.Decimal value);
        partial void OnAddedValuePercentChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SesaModel", "InternalProductProductMaterial", "ProductMaterialTable")]
        public EntityCollection<InternalProductMaterial> InternalProductMaterials
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<InternalProductMaterial>("SesaModel.InternalProductProductMaterial", "ProductMaterialTable");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<InternalProductMaterial>("SesaModel.InternalProductProductMaterial", "ProductMaterialTable", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SesaModel", "ProductProductionTestimony", "ProductionTestimony")]
        public EntityCollection<Testimony> Testimonies
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Testimony>("SesaModel.ProductProductionTestimony", "ProductionTestimony");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Testimony>("SesaModel.ProductProductionTestimony", "ProductionTestimony", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SesaModel", "ProductExternalProductMaterial", "ExternalProductMaterial")]
        public EntityCollection<ExternalProductMaterial> ExternalProductMaterial
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ExternalProductMaterial>("SesaModel.ProductExternalProductMaterial", "ExternalProductMaterial");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ExternalProductMaterial>("SesaModel.ProductExternalProductMaterial", "ExternalProductMaterial", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SesaModel", Name="Testimony")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Testimony : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Testimony object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="productCount">Initial value of the ProductCount property.</param>
        /// <param name="packingType">Initial value of the PackingType property.</param>
        /// <param name="pureWeight">Initial value of the PureWeight property.</param>
        /// <param name="realWeight">Initial value of the RealWeight property.</param>
        /// <param name="requestNumber">Initial value of the RequestNumber property.</param>
        /// <param name="requestDate">Initial value of the RequestDate property.</param>
        /// <param name="headerNumber">Initial value of the HeaderNumber property.</param>
        /// <param name="headerDate">Initial value of the HeaderDate property.</param>
        public static Testimony CreateTestimony(global::System.Guid id, global::System.Int32 productCount, global::System.String packingType, global::System.Decimal pureWeight, global::System.Decimal realWeight, global::System.String requestNumber, global::System.String requestDate, global::System.String headerNumber, global::System.String headerDate)
        {
            Testimony testimony = new Testimony();
            testimony.Id = id;
            testimony.ProductCount = productCount;
            testimony.PackingType = packingType;
            testimony.PureWeight = pureWeight;
            testimony.RealWeight = realWeight;
            testimony.RequestNumber = requestNumber;
            testimony.RequestDate = requestDate;
            testimony.HeaderNumber = headerNumber;
            testimony.HeaderDate = headerDate;
            return testimony;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProductCount
        {
            get
            {
                return _ProductCount;
            }
            set
            {
                OnProductCountChanging(value);
                ReportPropertyChanging("ProductCount");
                _ProductCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProductCount");
                OnProductCountChanged();
            }
        }
        private global::System.Int32 _ProductCount;
        partial void OnProductCountChanging(global::System.Int32 value);
        partial void OnProductCountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PackingType
        {
            get
            {
                return _PackingType;
            }
            set
            {
                OnPackingTypeChanging(value);
                ReportPropertyChanging("PackingType");
                _PackingType = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PackingType");
                OnPackingTypeChanged();
            }
        }
        private global::System.String _PackingType;
        partial void OnPackingTypeChanging(global::System.String value);
        partial void OnPackingTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal PureWeight
        {
            get
            {
                return _PureWeight;
            }
            set
            {
                OnPureWeightChanging(value);
                ReportPropertyChanging("PureWeight");
                _PureWeight = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PureWeight");
                OnPureWeightChanged();
            }
        }
        private global::System.Decimal _PureWeight;
        partial void OnPureWeightChanging(global::System.Decimal value);
        partial void OnPureWeightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal RealWeight
        {
            get
            {
                return _RealWeight;
            }
            set
            {
                OnRealWeightChanging(value);
                ReportPropertyChanging("RealWeight");
                _RealWeight = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RealWeight");
                OnRealWeightChanged();
            }
        }
        private global::System.Decimal _RealWeight;
        partial void OnRealWeightChanging(global::System.Decimal value);
        partial void OnRealWeightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RequestNumber
        {
            get
            {
                return _RequestNumber;
            }
            set
            {
                OnRequestNumberChanging(value);
                ReportPropertyChanging("RequestNumber");
                _RequestNumber = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RequestNumber");
                OnRequestNumberChanged();
            }
        }
        private global::System.String _RequestNumber;
        partial void OnRequestNumberChanging(global::System.String value);
        partial void OnRequestNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RequestDate
        {
            get
            {
                return _RequestDate;
            }
            set
            {
                OnRequestDateChanging(value);
                ReportPropertyChanging("RequestDate");
                _RequestDate = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RequestDate");
                OnRequestDateChanged();
            }
        }
        private global::System.String _RequestDate;
        partial void OnRequestDateChanging(global::System.String value);
        partial void OnRequestDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String HeaderNumber
        {
            get
            {
                return _HeaderNumber;
            }
            set
            {
                OnHeaderNumberChanging(value);
                ReportPropertyChanging("HeaderNumber");
                _HeaderNumber = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("HeaderNumber");
                OnHeaderNumberChanged();
            }
        }
        private global::System.String _HeaderNumber;
        partial void OnHeaderNumberChanging(global::System.String value);
        partial void OnHeaderNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String HeaderDate
        {
            get
            {
                return _HeaderDate;
            }
            set
            {
                OnHeaderDateChanging(value);
                ReportPropertyChanging("HeaderDate");
                _HeaderDate = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("HeaderDate");
                OnHeaderDateChanged();
            }
        }
        private global::System.String _HeaderDate;
        partial void OnHeaderDateChanging(global::System.String value);
        partial void OnHeaderDateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SesaModel", "ProductProductionTestimony", "Product")]
        public Product Product
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("SesaModel.ProductProductionTestimony", "Product").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("SesaModel.ProductProductionTestimony", "Product").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Product> ProductReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("SesaModel.ProductProductionTestimony", "Product");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Product>("SesaModel.ProductProductionTestimony", "Product", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SesaModel", "TestimonyTestimonyDetail", "TestimonyDetail")]
        public EntityCollection<TestimonyDetail> TestimonyDetails
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TestimonyDetail>("SesaModel.TestimonyTestimonyDetail", "TestimonyDetail");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TestimonyDetail>("SesaModel.TestimonyTestimonyDetail", "TestimonyDetail", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SesaModel", Name="TestimonyDetail")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TestimonyDetail : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TestimonyDetail object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="value">Initial value of the Value property.</param>
        /// <param name="isInternal">Initial value of the IsInternal property.</param>
        /// <param name="weight">Initial value of the Weight property.</param>
        public static TestimonyDetail CreateTestimonyDetail(global::System.Guid id, global::System.Decimal value, global::System.Boolean isInternal, global::System.Decimal weight)
        {
            TestimonyDetail testimonyDetail = new TestimonyDetail();
            testimonyDetail.Id = id;
            testimonyDetail.Value = value;
            testimonyDetail.IsInternal = isInternal;
            testimonyDetail.Weight = weight;
            return testimonyDetail;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Value
        {
            get
            {
                return _Value;
            }
            set
            {
                OnValueChanging(value);
                ReportPropertyChanging("Value");
                _Value = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Value");
                OnValueChanged();
            }
        }
        private global::System.Decimal _Value;
        partial void OnValueChanging(global::System.Decimal value);
        partial void OnValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsInternal
        {
            get
            {
                return _IsInternal;
            }
            set
            {
                OnIsInternalChanging(value);
                ReportPropertyChanging("IsInternal");
                _IsInternal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsInternal");
                OnIsInternalChanged();
            }
        }
        private global::System.Boolean _IsInternal;
        partial void OnIsInternalChanging(global::System.Boolean value);
        partial void OnIsInternalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Weight
        {
            get
            {
                return _Weight;
            }
            set
            {
                OnWeightChanging(value);
                ReportPropertyChanging("Weight");
                _Weight = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Weight");
                OnWeightChanged();
            }
        }
        private global::System.Decimal _Weight;
        partial void OnWeightChanging(global::System.Decimal value);
        partial void OnWeightChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SesaModel", "TestimonyTestimonyDetail", "Testimony")]
        public Testimony Testimony
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Testimony>("SesaModel.TestimonyTestimonyDetail", "Testimony").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Testimony>("SesaModel.TestimonyTestimonyDetail", "Testimony").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Testimony> TestimonyReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Testimony>("SesaModel.TestimonyTestimonyDetail", "Testimony");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Testimony>("SesaModel.TestimonyTestimonyDetail", "Testimony", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SesaModel", "WarehouseBillTestimonyDetail", "WarehouseBill")]
        public WarehouseBill WarehouseBill
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<WarehouseBill>("SesaModel.WarehouseBillTestimonyDetail", "WarehouseBill").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<WarehouseBill>("SesaModel.WarehouseBillTestimonyDetail", "WarehouseBill").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<WarehouseBill> WarehouseBillReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<WarehouseBill>("SesaModel.WarehouseBillTestimonyDetail", "WarehouseBill");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<WarehouseBill>("SesaModel.WarehouseBillTestimonyDetail", "WarehouseBill", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SesaModel", "MaterialTestimonyDetail", "Material")]
        public Material Material
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Material>("SesaModel.MaterialTestimonyDetail", "Material").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Material>("SesaModel.MaterialTestimonyDetail", "Material").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Material> MaterialReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Material>("SesaModel.MaterialTestimonyDetail", "Material");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Material>("SesaModel.MaterialTestimonyDetail", "Material", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SesaModel", Name="Unit")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Unit : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Unit object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="symbol">Initial value of the Symbol property.</param>
        /// <param name="caption">Initial value of the Caption property.</param>
        public static Unit CreateUnit(global::System.Guid id, global::System.String symbol, global::System.String caption)
        {
            Unit unit = new Unit();
            unit.Id = id;
            unit.Symbol = symbol;
            unit.Caption = caption;
            return unit;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Symbol
        {
            get
            {
                return _Symbol;
            }
            set
            {
                OnSymbolChanging(value);
                ReportPropertyChanging("Symbol");
                _Symbol = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Symbol");
                OnSymbolChanged();
            }
        }
        private global::System.String _Symbol;
        partial void OnSymbolChanging(global::System.String value);
        partial void OnSymbolChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Caption
        {
            get
            {
                return _Caption;
            }
            set
            {
                OnCaptionChanging(value);
                ReportPropertyChanging("Caption");
                _Caption = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Caption");
                OnCaptionChanged();
            }
        }
        private global::System.String _Caption;
        partial void OnCaptionChanging(global::System.String value);
        partial void OnCaptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BaseCoefficient
        {
            get
            {
                return _BaseCoefficient;
            }
            set
            {
                OnBaseCoefficientChanging(value);
                ReportPropertyChanging("BaseCoefficient");
                _BaseCoefficient = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BaseCoefficient");
                OnBaseCoefficientChanged();
            }
        }
        private global::System.String _BaseCoefficient;
        partial void OnBaseCoefficientChanging(global::System.String value);
        partial void OnBaseCoefficientChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> BaseUnit_Id
        {
            get
            {
                return _BaseUnit_Id;
            }
            set
            {
                OnBaseUnit_IdChanging(value);
                ReportPropertyChanging("BaseUnit_Id");
                _BaseUnit_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BaseUnit_Id");
                OnBaseUnit_IdChanged();
            }
        }
        private Nullable<global::System.Guid> _BaseUnit_Id;
        partial void OnBaseUnit_IdChanging(Nullable<global::System.Guid> value);
        partial void OnBaseUnit_IdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SesaModel", "UnitMaterial", "Material")]
        public EntityCollection<Material> Materials
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Material>("SesaModel.UnitMaterial", "Material");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Material>("SesaModel.UnitMaterial", "Material", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SesaModel", "UnitWarehouseBillDetail", "WarehouseBillDetail")]
        public EntityCollection<WarehouseBillDetail> WarehouseBillDetails
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<WarehouseBillDetail>("SesaModel.UnitWarehouseBillDetail", "WarehouseBillDetail");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<WarehouseBillDetail>("SesaModel.UnitWarehouseBillDetail", "WarehouseBillDetail", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SesaModel", "FK_BaseUnit_DerivedUnit", "Unit1")]
        public EntityCollection<Unit> DerivedUnits
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Unit>("SesaModel.FK_BaseUnit_DerivedUnit", "Unit1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Unit>("SesaModel.FK_BaseUnit_DerivedUnit", "Unit1", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SesaModel", "FK_BaseUnit_DerivedUnit", "Unit")]
        public Unit BaseUnit
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Unit>("SesaModel.FK_BaseUnit_DerivedUnit", "Unit").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Unit>("SesaModel.FK_BaseUnit_DerivedUnit", "Unit").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Unit> BaseUnitReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Unit>("SesaModel.FK_BaseUnit_DerivedUnit", "Unit");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Unit>("SesaModel.FK_BaseUnit_DerivedUnit", "Unit", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SesaModel", Name="WarehouseBill")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class WarehouseBill : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new WarehouseBill object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="rowNumber">Initial value of the RowNumber property.</param>
        /// <param name="emissionDate">Initial value of the EmissionDate property.</param>
        /// <param name="isInternal">Initial value of the IsInternal property.</param>
        public static WarehouseBill CreateWarehouseBill(global::System.Guid id, global::System.String rowNumber, global::System.String emissionDate, global::System.Boolean isInternal)
        {
            WarehouseBill warehouseBill = new WarehouseBill();
            warehouseBill.Id = id;
            warehouseBill.RowNumber = rowNumber;
            warehouseBill.EmissionDate = emissionDate;
            warehouseBill.IsInternal = isInternal;
            return warehouseBill;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RowNumber
        {
            get
            {
                return _RowNumber;
            }
            set
            {
                OnRowNumberChanging(value);
                ReportPropertyChanging("RowNumber");
                _RowNumber = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RowNumber");
                OnRowNumberChanged();
            }
        }
        private global::System.String _RowNumber;
        partial void OnRowNumberChanging(global::System.String value);
        partial void OnRowNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EmissionDate
        {
            get
            {
                return _EmissionDate;
            }
            set
            {
                OnEmissionDateChanging(value);
                ReportPropertyChanging("EmissionDate");
                _EmissionDate = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EmissionDate");
                OnEmissionDateChanged();
            }
        }
        private global::System.String _EmissionDate;
        partial void OnEmissionDateChanging(global::System.String value);
        partial void OnEmissionDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsInternal
        {
            get
            {
                return _IsInternal;
            }
            set
            {
                OnIsInternalChanging(value);
                ReportPropertyChanging("IsInternal");
                _IsInternal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsInternal");
                OnIsInternalChanged();
            }
        }
        private global::System.Boolean _IsInternal;
        partial void OnIsInternalChanging(global::System.Boolean value);
        partial void OnIsInternalChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SesaModel", "WarehouseBillWarehouseBillDetail", "WarehouseBillDetail")]
        public EntityCollection<WarehouseBillDetail> WarehouseBillDetails
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<WarehouseBillDetail>("SesaModel.WarehouseBillWarehouseBillDetail", "WarehouseBillDetail");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<WarehouseBillDetail>("SesaModel.WarehouseBillWarehouseBillDetail", "WarehouseBillDetail", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SesaModel", "WarehouseBillTestimonyDetail", "TestimonyDetail")]
        public EntityCollection<TestimonyDetail> TestimonyDetails
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TestimonyDetail>("SesaModel.WarehouseBillTestimonyDetail", "TestimonyDetail");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TestimonyDetail>("SesaModel.WarehouseBillTestimonyDetail", "TestimonyDetail", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SesaModel", Name="WarehouseBillDetail")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class WarehouseBillDetail : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new WarehouseBillDetail object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="value">Initial value of the Value property.</param>
        /// <param name="weight">Initial value of the Weight property.</param>
        public static WarehouseBillDetail CreateWarehouseBillDetail(global::System.Guid id, global::System.Decimal value, global::System.Decimal weight)
        {
            WarehouseBillDetail warehouseBillDetail = new WarehouseBillDetail();
            warehouseBillDetail.Id = id;
            warehouseBillDetail.Value = value;
            warehouseBillDetail.Weight = weight;
            return warehouseBillDetail;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Value
        {
            get
            {
                return _Value;
            }
            set
            {
                OnValueChanging(value);
                ReportPropertyChanging("Value");
                _Value = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Value");
                OnValueChanged();
            }
        }
        private global::System.Decimal _Value;
        partial void OnValueChanging(global::System.Decimal value);
        partial void OnValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Weight
        {
            get
            {
                return _Weight;
            }
            set
            {
                OnWeightChanging(value);
                ReportPropertyChanging("Weight");
                _Weight = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Weight");
                OnWeightChanged();
            }
        }
        private global::System.Decimal _Weight;
        partial void OnWeightChanging(global::System.Decimal value);
        partial void OnWeightChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SesaModel", "MaterialWarehouseBillDetail", "Material")]
        public Material Material
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Material>("SesaModel.MaterialWarehouseBillDetail", "Material").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Material>("SesaModel.MaterialWarehouseBillDetail", "Material").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Material> MaterialReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Material>("SesaModel.MaterialWarehouseBillDetail", "Material");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Material>("SesaModel.MaterialWarehouseBillDetail", "Material", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SesaModel", "WarehouseBillWarehouseBillDetail", "WarehouseBill")]
        public WarehouseBill WarehouseBill
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<WarehouseBill>("SesaModel.WarehouseBillWarehouseBillDetail", "WarehouseBill").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<WarehouseBill>("SesaModel.WarehouseBillWarehouseBillDetail", "WarehouseBill").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<WarehouseBill> WarehouseBillReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<WarehouseBill>("SesaModel.WarehouseBillWarehouseBillDetail", "WarehouseBill");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<WarehouseBill>("SesaModel.WarehouseBillWarehouseBillDetail", "WarehouseBill", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SesaModel", "UnitWarehouseBillDetail", "Unit")]
        public Unit Unit
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Unit>("SesaModel.UnitWarehouseBillDetail", "Unit").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Unit>("SesaModel.UnitWarehouseBillDetail", "Unit").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Unit> UnitReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Unit>("SesaModel.UnitWarehouseBillDetail", "Unit");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Unit>("SesaModel.UnitWarehouseBillDetail", "Unit", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
